name: Deploy

permissions:
  contents: write

on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'

      - name: Install Node.js dependencies
        run: npm clean-install

      - name: Build presets
        run: npm run dist

      - name: Update translations files
        run: npm run translations

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: "Checkout tools repo"
        uses: actions/checkout@v6
        with:
            repository: nlehuby/alm_profile_builder
            path: profile_builder

      - name: Build profiles
        run: |
            cd ./profile_builder
            python main.py ../dist/presets.json ../data/profiles.json -o ../dist -u ''
            rm ../dist/presets.min.json
            cp ../dist/cnig_mandatory.json ../dist/presets.min.json
            mkdir -p output/dist
            cp -r ../dist/* output/dist

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: profile_builder/output
            enable_jekyll: true
